trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform Azure!
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azurersa.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    #commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'Azure-rm-sc'
    backendAzureRmSubscriptionId: '04baf33a-4623-40c7-9c29-06a038af2c98'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rm'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'acbsalablo'
    backendAzureRmContainerName: 'acbsalablo'
    backendAzureRmKey: 'kubernetes-lab.tfstate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'Azure-rm-sc'
    providerAzureRmSubscriptionId: '04baf33a-4623-40c7-9c29-06a038af2c98'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    allowTelemetryCollection: true
